name: 'testing'
on:
  push:
    branches:
      -main
  commit:
    branches:
      -main
      
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/test@v3
