  name: CI

  on:
    push:
      branches: [ main2 ]
    pull_request:
      branches: [ main2 ]

  jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other a,
          echo test, and 
